name: CMR Vision CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: cmr-vision/package-lock.json
    
    - name: Check file structure
      run: |
        echo "Checking directory structure..."
        ls -la
        echo "Checking cmr-vision directory..."
        ls -la cmr-vision
    
    - name: Install dependencies
      working-directory: ./cmr-vision
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Installing TypeScript types..."
        npm install --save-dev @types/three @types/react @types/react-dom typescript
    
    - name: Build
      working-directory: ./cmr-vision
      run: |
        echo "Starting build process..."
        CI=false npm run build
      
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: cmr-vision/build
        retention-days: 5
      
    # Optional deployment steps
    # - name: Deploy to GitHub Pages
    #   if: success() && github.ref == 'refs/heads/main'
    #   uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     branch: gh-pages
    #     folder: cmr-vision/build 